# Generated by Django 4.1.3 on 2022-11-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=32)),
                ('commonName', models.CharField(max_length=64)),
                ('wiki', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('size', models.IntegerField()),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mappingAPI.parks')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappingAPI.treespecies')),
            ],
        ),
        migrations.CreateModel(
            name='TreePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mappingAPI.trees')),
            ],
        ),
    ]
