# Generated by Django 4.1.3 on 2022-11-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappingAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parks',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=48.76, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parks',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=-122.490773, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parks',
            name='zoom',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
