# Generated by Django 4.1.3 on 2022-11-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappingAPI', '0002_parks_lat_parks_lng_parks_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treephotos',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappingAPI.trees'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mappingAPI.treespecies'),
        ),
        migrations.CreateModel(
            name='TreeNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('text', models.CharField(max_length=128)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappingAPI.trees')),
            ],
        ),
    ]
