version: "2.14.1"
services:
  ui: 
    build: ./frontend/
    ports: 
      - "3000:3000"
    command: node build
    restart: always
  api:
    build: ./backend/
    ports: 
      - "8000:8000"
    command: waitress-serve --listen="0.0.0.0:8000" treeMapperAPI.wsgi:application
    volumes: 
      - ./backend:/app
    restart: always
